### ISSUE TITLE
French

### ISSUE THREAD

**Issue by jamesryanbell** [bnspayments/magento2-language-en-gb#3]
Hi

There seems to be a large amount of translation that is in French rather than en_GB, e.g. en_gb.module.magento_sales.csv is almost entirely in French.

Thanks,
James

**Comment by bnspayments** [comment]
Apologies, the original maintainer of the branch has left us and as yet no-one has picked it up. There was a tri language  pack proposed to provide GB, FR and DE for Magento 2. 

I am going to flag this in the project so that others can pick up where he'd got to.
